# file for Carton (aka bundler)
# http://search.cpan.org/~miyagawa/Carton-v1.0.12/lib/Carton.pm
requires 'perl', '5.10.1';

requires 'JavaScript::Minifier::XS'   => 0;
requires 'Socket'                     => 0;
requires 'CSS::Minifier::XS'          => 0;
requires 'Crypt::Eksblowfish::Bcrypt' => 0;
requires 'Plack'                      => 0;
requires 'Starman'                    => 0;
